[tools]
go = "1.25.3"
kubectl = "1.30.2"
"go:github.com/onsi/ginkgo/v2/ginkgo" = "2.19.0"
kind = "0.22.0"
crc = "2.39.0"
kubebuilder = "4.8.0"

[alias]
# Need to use Barak's fork until PR#8 is merged upstream
crc = 'https://github.com/ifireball/asdf-crc#revert-bkorren-fix'
